apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    # Your Prometheus configuration here
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'prometheus'
    # Additional configuration as needed
