
apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: murulii/register-app-pipeline:1.0-18
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: url
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db          
          
          
          #env:
          #  - name: MYSQL_HOST
          #    value: "mysql-service"          # this is your mysql's service clusture IP, Make sure to change it with yours
          #  - name: MYSQL_PASSWORD
          #    value: "root"
          #  - name: MYSQL_USER
           #   value: "root"
           # - name: MYSQL_DB
           #   value: "default_db"



          
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
        
