apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  selector:
    app: register-app

  ports:
    - port: 80
      targetPort: 5000

  type: NodePort
