server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://100.25.182.227:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://100.25.182.227:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://100.25.182.227:1003/api/v1
    cart:
      path: /cart/**
      url: http://100.25.182.227:1004/api/v1
