server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://${offer_api_ip}:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://${shoe_api_ip}:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://${wishlist_api_ip}:1003
    cart:
      path: /cart/**
      url: http://${cart_api_ip}:1004/api/v1
